model:
  type: FR_UNet
  args:
    {}
# loss: BCELoss, CE_DiceLoss, Soft_clDice, DiceLoss, 
loss:
  type: CE_DiceLoss
  args:
    {}

dataset:
  type: DRIVE
  path: /mnt/qb/berens/users/jfadugba97/RetinaSegmentation/datasets/FIVES
  args:
    {}
  
optimizer:
  type: Adam
  args:
    lr: 1e-3
    weight_decay: 1e-5

lr_scheduler:
  type: CosineAnnealingLR
  args:
    T_max: 40
    
# Data config
size: 512
batch_size: 4
random_seed: 23
num_workers: 8
epochs: 80
save_dir: /mnt/qb/berens/users/jfadugba97/RetinaSegmentation/model_results/FR_UNet/
val_per_epochs: 1
save_period: 5

tensorboard: true
threshold: 0.5
threshold_low: 0.3
DTI: false
amp: true # automatic mixed precision
tta: false
CCC: false